"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG',  cast=bool)

ALLOWED_HOSTS = []

RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default=None, cast=str)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


MEDIA_URL = '/media/' # * URL para acceder a los archivos multimedia
MEDIA_ROOT = BASE_DIR / 'media' # * Ruta donde se guardarán los archivos multimedia

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com') # * Servidor SMTP de Gmail
EMAIL_PORT = config('EMAIL_PORT', cast=int) # * Puerto SMTP
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool) # * Usar TLS para la conexión segura
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='tu_correo@gmail.com') # * Cambia esto por tu correo de Gmail
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='TU_CONTRASEÑA_DE_APLICACION') # * Cambia esto por tu contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# Configuración de Cloudinary para almacenamiento de archivos multimedia

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



# Application definition

INSTALLED_APPS = [
    # ^ apps de django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'cloudinary_storage',
    'cloudinary',
    
    # ^ apps de terceros
    'rest_framework',
    "corsheaders", # * Permite solicitudes CORS desde el frontend
    'rest_framework.authtoken',
    
    # ^ apps locales
    'core',
]

MIDDLEWARE = [
    
    "corsheaders.middleware.CorsMiddleware", # * Middleware para manejar CORS
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # * Middleware para servir archivos estáticos en producción
    
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # * Motor de base de datos PostgreSQL
        # * Configuración para trabajar en producción con Clever Cloud
        'NAME': config('DB_NAME'), # * Nombre de la base de datos
        'USER': config('DB_USER'), # * Usuario de la base de datos
        'PASSWORD': config('DB_PASSWORD'), # * Contraseña de la base de datos
        'HOST': config('DB_HOST'), # * Host de la base de datos
        'PORT': config('DB_PORT', cast=int), # * Puerto de la base de datos
    }
    # * Configuración para trabajar en local con PostgreSQL
    # !   {
    # !   'ENGINE': 'django.db.backends.postgresql',
    # !   'NAME': 'grupomcsolar',
    # !   'USER': 'admin',
    # !   'PASSWORD': '222835',
    # !   'HOST': 'localhost',
    # !   'PORT': '5432',
    # !   } 
}

CORS_ALLOWED_ORIGINS = [ # * Permite solicitudes CORS desde el frontend
    #"http://localhost:3000",
    #"http://localhost:9002",
    #"http://192.168.56.1:9002",# * Next.js en desarrollo
    # * Si vas a subirlo a producción, añade aquí tu dominio real:
     "https://proyecto-pagina-solar.vercel.app",
     "https://proyecto-pagina-solar-jbfeum1tn-manuelh28s-projects.vercel.app",
     "https://proyecto-pagina-solar-eta.vercel.app/",
     
     
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
