"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)!v0wg8f2v6x1a+@r8bko6+w09lo_krtc8e81&3)2=+i&ob0(e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']


MEDIA_URL = '/media/' # * URL para acceder a los archivos multimedia
MEDIA_ROOT = BASE_DIR / 'media' # * Ruta donde se guardarán los archivos multimedia

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "tu_correo@gmail.com" # * Cambia esto por tu correo de Gmail
EMAIL_HOST_PASSWORD = "TU_CONTRASEÑA_DE_APLICACION" # * Cambia esto por tu contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"



# Application definition

INSTALLED_APPS = [
    # ^ apps de django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # ^ apps de terceros
    'rest_framework',
    "corsheaders", # * Permite solicitudes CORS desde el frontend
    'rest_framework.authtoken',
    
    # ^ apps locales
    'core',
]

MIDDLEWARE = [
    
    "corsheaders.middleware.CorsMiddleware", # * Middleware para manejar CORS
    'django.middleware.common.CommonMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # * Motor de base de datos PostgreSQL
        # * Configuración para trabajar en producción con Clever Cloud
        'NAME': 'b2ejckpoxq9au5cvzbfn', # * Nombre de la base de datos
        'USER': 'ukkmthdrlq1rkf2ju6g2', # * Usuario de la base de datos
        'PASSWORD': 'e09Y1SWuJZURW1vHNyIJ3ynVcafdLd', # * Contraseña de la base de datos
        'HOST': 'b2ejckpoxq9au5cvzbfn-postgresql.services.clever-cloud.com', # * Host de la base de datos
        'PORT': 5432, # * Puerto de la base de datos
    }
    # * Configuración para trabajar en local con PostgreSQL
    # !   {
    # !   'ENGINE': 'django.db.backends.postgresql',
    # !   'NAME': 'grupomcsolar',
    # !   'USER': 'admin',
    # !   'PASSWORD': '222835',
    # !   'HOST': 'localhost',
    # !   'PORT': '5432',
    # !   } 
}

CORS_ALLOWED_ORIGINS = [ # * Permite solicitudes CORS desde el frontend
    "http://localhost:3000",
    "http://localhost:9002",
    "http://192.168.56.1:9002",# * Next.js en desarrollo
    # * Si vas a subirlo a producción, añade aquí tu dominio real:
     "https://proyecto-pagina-solar.vercel.app/"
    
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
